import * as Ed25519Multikey from '@digitalbazaar/ed25519-multikey';
import { createSignCryptosuite } from '@digitalbazaar/eddsa-jcs-2022-cryptosuite';
import { base58btc } from 'multiformats/bases/base58';
import type {
  ResolvedDidDocument,
  UnsecuredPlatformIdentityCredential,
  UnverifiedPlatformIdentityCredential,
} from './types.js';

const ISSUER = 'did:web:issuer.example';
const KEY_ID = `${ISSUER}#key-1`;

type SignCryptosuite = {
  name: string;
  createVerifyData(input: {
    cryptosuite: SignCryptosuite;
    document: Record<string, unknown>;
    proof: Record<string, unknown>;
  }): Promise<Uint8Array>;
};

/**
 * Provisional local #613 fixture generator.
 *
 * The seed and semantic input are fixed, and the proof is generated by the
 * pinned Digital Bazaar eddsa-jcs-2022 implementation. Replace this helper
 * with #613's revision/hash-pinned public fixtures once they are published.
 */
export async function createIdentityVcFixture(overrides: {
  domain?: string;
  challenge?: string;
  validFrom?: string;
  validUntil?: string;
  mutateUnsecured?: (credential: UnsecuredPlatformIdentityCredential) => void;
} = {}): Promise<{
  credential: UnverifiedPlatformIdentityCredential;
  didDocument: ResolvedDidDocument;
}> {
  const key = await Ed25519Multikey.generate({ seed: new Uint8Array(32).fill(7) });
  key.id = KEY_ID;
  key.controller = ISSUER;
  const publicKey = await key.export({ publicKey: true });
  const didDocument: ResolvedDidDocument = {
    '@context': ['https://www.w3.org/ns/did/v1', 'https://w3id.org/security/multikey/v1'],
    id: ISSUER,
    verificationMethod: [publicKey],
    assertionMethod: [KEY_ID],
  };
  const unsecured: UnsecuredPlatformIdentityCredential = {
    '@context': [
      'https://www.w3.org/ns/credentials/v2',
      'https://mentionable.dev/ns/identity/v0.2/context.jsonld',
    ],
    id: 'urn:uuid:5d01e4c8-5907-4de5-976a-b60086233525',
    type: ['VerifiableCredential', 'PlatformIdentityCredential'],
    issuer: ISSUER,
    validFrom: overrides.validFrom ?? '2026-08-18T13:55:00.000Z',
    validUntil: overrides.validUntil ?? '2026-08-18T14:05:00.000Z',
    credentialSubject: {
      id: 'slack:T123/U456',
      method: 'urn:mentionable:auth:slack-workspace-member:v0.1',
      assurance: 'platform',
      platform: { provider: 'slack', workspace_id: 'T123', channelId: 'discard-me' },
      observedInvocation: { target: '@agent@bridge.example', threadId: 'discard-me' },
      profile: {
        display_name: 'Alice',
        username: 'alice',
        avatar: 'https://private.example/avatar',
      },
      source: { raw: 'discard-me' },
    },
  };
  const proof: Record<string, unknown> = {
    type: 'DataIntegrityProof',
    cryptosuite: 'eddsa-jcs-2022',
    created: '2026-08-18T14:00:00.000Z',
    verificationMethod: KEY_ID,
    proofPurpose: 'assertionMethod',
    domain: overrides.domain ?? '@agent@bridge.example',
    challenge: overrides.challenge ?? 'message-1',
  };
  overrides.mutateUnsecured?.(unsecured);
  const suite = createSignCryptosuite() as SignCryptosuite;
  const data = await suite.createVerifyData({
    cryptosuite: suite,
    document: structuredClone(unsecured) as unknown as Record<string, unknown>,
    proof,
  });
  proof.proofValue = base58btc.encode(await key.signer().sign({ data }));

  return {
    credential: { ...unsecured, proof } as UnverifiedPlatformIdentityCredential,
    didDocument,
  };
}
