// Shared by host inspect validation and the workload relay. Match names only.
export const PROVIDER_ENV_PATTERN = /^(ANTHROPIC_|CLAUDE_CODE_OAUTH|CLAUDE_CODE_USE_|OPENAI_|CODEX_API_KEY$|AWS_|AZURE_|GOOGLE_|GEMINI_|GROQ_|MISTRAL_|COHERE_|HF_TOKEN$|HUGGING_FACE_HUB_TOKEN$)|(?:^|_)(?:API_KEY|ACCESS_TOKEN|REFRESH_TOKEN|SECRET_KEY|PRIVATE_KEY|CREDENTIALS)$/;
