// `vicoop-client setup` — create a bridge client token using an existing
// owner-session bearer, then write the daemon env file.

import { atomicWriteFile, resolveOwnerSession } from './owner-session.js';

interface SetupArgs {
  clientName: string;
  allowedAgentIds: string[];
  callers: string[];
  envFile: string | null;
  bridge?: string;
  token?: string;
  json: boolean;
}

interface RegisterClientGraphQLResponse {
  data?: {
    registerClient?: {
      clientWithToken?: {
        id: string;
        token: string;
        ownerPrincipal: string;
        allowedAgentIds: string[];
      };
    };
  };
  errors?: Array<{ message?: string }>;
}

interface ClientRegisterSuccess {
  intent: 'client_register';
  client_id: string;
  client_token: string;
  owner_principal: string;
  client_name: string;
  allowed_agent_ids: string[];
}

function usage(): string {
  return [
    'usage: vicoop-client setup --client-name <name> --agent-ids <id1,id2>',
    '                           [--caller PRINCIPAL]... [--write-env-file <path>]',
    '                           [--bridge URL] [--token TOKEN] [--json]',
  ].join('\n');
}

function parseArgs(args: string[]): SetupArgs | { error: string; help?: boolean } {
  let clientName: string | undefined;
  let allowedAgentIds: string[] = [];
  const callers: string[] = [];
  let envFile: string | null = null;
  let bridge: string | undefined;
  let token: string | undefined;
  let json = false;

  for (let i = 0; i < args.length; i++) {
    const a = args[i];
    if (a === '--json') {
      json = true;
      continue;
    }
    if (a === '-h' || a === '--help') {
      return { error: '', help: true };
    }
    const v = args[i + 1];
    if (v === undefined) return { error: `${a} requires a value` };
    switch (a) {
      case '--client-name':
        clientName = v;
        break;
      case '--agent-ids':
        allowedAgentIds = v.split(',').map((s) => s.trim()).filter(Boolean);
        break;
      case '--caller':
        callers.push(...v.split(',').map((s) => s.trim()).filter(Boolean));
        break;
      case '--write-env-file':
      case '--env-file':
        envFile = v;
        break;
      case '--bridge':
        bridge = v;
        break;
      case '--token':
        token = v;
        break;
      default:
        return { error: `unknown flag: ${a}` };
    }
    i++;
  }

  if (!clientName) return { error: '--client-name is required' };
  if (allowedAgentIds.length === 0) return { error: '--agent-ids is required' };
  return { clientName, allowedAgentIds, callers, envFile, bridge, token, json };
}

function gqlString(value: string): string {
  return JSON.stringify(value);
}

function gqlStringArray(values: string[]): string {
  return `[${values.map(gqlString).join(',')}]`;
}

function writeClientEnvFile(path: string, success: ClientRegisterSuccess, bridgeUrl: string): void {
  atomicWriteFile(path, [
    `# vicoop-client env (generated by 'vicoop-client setup')`,
    `SERVER_URL=${bridgeUrl.replace(/^http(s?):\/\//, (_m, s) => (s === 's' ? 'wss://' : 'ws://'))}`,
    `SERVER_TOKEN=${success.client_token}`,
    `AGENT_ID=${success.allowed_agent_ids[0] ?? ''}`,
    '',
  ].join('\n'), 0o600);
}

async function registerClient(
  session: { bridge: string; token: string },
  args: SetupArgs,
): Promise<ClientRegisterSuccess> {
  const query =
    'mutation{' +
    'registerClient(input:{' +
    `clientName:${gqlString(args.clientName)},` +
    `allowedAgentIds:${gqlStringArray(args.allowedAgentIds)}` +
    '}){clientWithToken{id token ownerPrincipal allowedAgentIds}}' +
    '}';

  const res = await fetch(`${session.bridge.replace(/\/$/, '')}/graphql`, {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${session.token}`,
      'content-type': 'application/json',
    },
    body: JSON.stringify({ query }),
  });
  const text = await res.text();
  let parsed: RegisterClientGraphQLResponse | null = null;
  try {
    parsed = JSON.parse(text) as RegisterClientGraphQLResponse;
  } catch {
    // handled below
  }
  if (!res.ok || parsed?.errors?.length) {
    const detail = parsed?.errors?.map((e) => e.message).filter(Boolean).join('; ') || text;
    throw new Error(`registerClient failed (${res.status}): ${detail}`);
  }
  const client = parsed?.data?.registerClient?.clientWithToken;
  if (!client?.id || !client.token || !client.ownerPrincipal || !client.allowedAgentIds) {
    throw new Error('registerClient returned an unexpected response');
  }
  return {
    intent: 'client_register',
    client_id: client.id,
    client_token: client.token,
    owner_principal: client.ownerPrincipal,
    client_name: args.clientName,
    allowed_agent_ids: client.allowedAgentIds,
  };
}

interface CallerSetupResult {
  agent_id?: string;
  principal?: string;
  allowed_callers?: string[];
}

async function addCaller(
  session: { bridge: string; token: string },
  agentId: string,
  principal: string,
): Promise<CallerSetupResult> {
  const res = await fetch(
    `${session.bridge.replace(/\/$/, '')}/admin-api/agents/${encodeURIComponent(agentId)}/callers`,
    {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${session.token}`,
        'content-type': 'application/json',
      },
      body: JSON.stringify({ principal }),
    },
  );
  const text = await res.text();
  let parsed: unknown = text;
  if (text) {
    try {
      parsed = JSON.parse(text) as unknown;
    } catch {
      // leave raw text
    }
  }
  if (!res.ok) {
    const detail =
      parsed && typeof parsed === 'object' && 'error' in parsed
        ? String((parsed as { error: unknown }).error)
        : String(parsed);
    throw new Error(`add-caller failed for ${agentId} (${res.status}): ${detail}`);
  }
  return parsed as CallerSetupResult;
}

async function configureCallers(
  session: { bridge: string; token: string },
  agentIds: string[],
  callers: string[],
): Promise<void> {
  for (const agentId of agentIds) {
    for (const caller of callers) {
      const result = await addCaller(session, agentId, caller);
      const configured = (result.allowed_callers ?? []).join(', ') || '(none)';
      process.stderr.write(
        `Configured caller for ${agentId}: ${result.principal ?? caller}\n` +
          `  allowed_callers   ${configured}\n`,
      );
    }
  }
}

export async function runSetup(args: string[]): Promise<number> {
  const parsed = parseArgs(args);
  if ('error' in parsed) {
    if (parsed.help) {
      process.stdout.write(`${usage()}\n`);
      return 0;
    }
    process.stderr.write(`${parsed.error}\n${usage()}\n`);
    return 1;
  }

  const stored = resolveOwnerSession();
  const bridge = parsed.bridge ?? stored?.bridge;
  const token = parsed.token ?? stored?.token;
  if (!bridge || !token) {
    process.stderr.write(
      'No owner-session bearer found. Run `vicoop-client login --bridge <URL>` first, ' +
        'or pass --bridge and --token explicitly (or set VICOOP_BRIDGE / VICOOP_OWNER_TOKEN).\n',
    );
    return 1;
  }

  let success: ClientRegisterSuccess;
  try {
    success = await registerClient({ bridge, token }, parsed);
  } catch (e) {
    process.stderr.write(`${(e as Error).message}\n`);
    return 1;
  }

  process.stderr.write(
    `  client_id        ${success.client_id}\n` +
      `  owner_principal  ${success.owner_principal}\n` +
      `  client_name      ${success.client_name}\n` +
      `  allowed_agents   ${success.allowed_agent_ids.join(', ')}\n\n` +
      'The CLIENT_TOKEN is shown only once and cannot be retrieved later.\n' +
      '  Save the setup output or env file now.\n\n',
  );

  if (parsed.callers.length > 0) {
    try {
      await configureCallers({ bridge, token }, success.allowed_agent_ids, parsed.callers);
    } catch (e) {
      process.stderr.write(`${(e as Error).message}\n`);
      return 1;
    }
    process.stderr.write('\n');
  } else {
    process.stderr.write(
      'WARNING: no callers configured. The agent is public until you run ' +
        '`vicoop-client add-caller <agent_id> <principal>`.\n\n',
    );
  }

  if (parsed.envFile) {
    writeClientEnvFile(parsed.envFile, success, bridge);
    process.stderr.write(`Wrote env block to ${parsed.envFile} (mode 600).\n`);
  } else if (parsed.json) {
    process.stdout.write(`${JSON.stringify(success, null, 2)}\n`);
  } else {
    const wsUrl = bridge.replace(/^http(s?):\/\//, (_m, s) => (s === 's' ? 'wss://' : 'ws://'));
    process.stdout.write([
      `SERVER_URL=${wsUrl}`,
      `SERVER_TOKEN=${success.client_token}`,
      `AGENT_ID=${success.allowed_agent_ids[0] ?? ''}`,
      '',
    ].join('\n'));
  }

  return 0;
}
